config/routes.rb
Signup::Application.routes.draw do
  get "welcome/index"
  post "user_steps/update_rzs"  => 'user_steps#update_rzs'

  resources :users
  resources :riskizations
  resources :user_steps
  resources :risks
  root to: 'welcome#index'
end

app/models/risk.rb
class Risk < ActiveRecord::Base
   attr_accessible :rtype, :risk, :result, :rver, :rposl
   
   has_many :riskizations
  has_many :users, :through => :riskizations
end

app/models/riskization.rb
class Riskization < ActiveRecord::Base
  
  attr_accessible :rver, :rposl, :mpred
  
  belongs_to :risk
  belongs_to :user
end

app/models/tph.rb
class Tph < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :bio, :date_of_birth, :email, :github_username, :name, :password, :password_confirmation, :twitter_username, :website, 
  :rabm, :oprab, :hlist, :lstand, :realst, :lrisk, :risk_ids, :rver, :rposl
  has_secure_password
  
  has_many :riskizations
  has_many :risks, :through => :riskizations
  
    
  validates_format_of :twitter_username, without: /\W/, allow_blank: true
  # validates_presence_of :twitter_username, if: :on_social_step?
  
  

def riskization_attributes=(riskization_attributes)
  riskization_attributes.each do |attributes|
    riskizations.build(attributes)
  end
end


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/riskizations_controller.rb
class RiskizationsController < ApplicationController
 
 attr_accessible :rver, :rposl
 
 attr_reader :totalpoint
 
 def update_rzs
    Riskization.update(params[:riskization].keys, params[:riskization].values)
    flash[:notice] = 'Reports were successfully updated.'
     redirect_to wizard_path(next_step), options
 end 
 

  def totalpoint
    rver + rposl
  end
  
end

app/controllers/risks_controller.rb
class RisksController < ApplicationController
  def index
    @risk = Risk.all
  end

  def new
    @risk = Risk.new
  end

  def create
    @risk = Risk.new(params[:risk])
    if @risk.save
      session[:risk_id] = @risk.id
      redirect_to risks_path
    else
      render :new
    end
  end
end

app/controllers/user_steps_controller.rb
class UserStepsController < ApplicationController
  include Wicked::Wizard
  steps :personal, :social, :social1, :social2, :social3, :social4
  
  def show
    @risk = Risk.all
    @user = current_user
    render_wizard
  end
  
  def update
    @user = current_user
    @user.attributes = params[:user]
    render_wizard @user
  end
  
  def update_rzs
    Riskization.update(params[:riskization].keys, params[:riskization].values)
    flash[:notice] = 'Reports were successfully updated.'
    if (session[:st] == 1)
      redirect_to_next(:social4)
    end
    if (session[:st] == 2)
      redirect_to_finish_wizard
    end  
 end 
  
private
  def redirect_to_finish_wizard(options = nil)
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def index
    @user = User.all
  end

  def new    
    @user = User.new
  end
  
  def show    
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_steps_path
    else
      render :new
    end
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/riskizations_helper.rb
module RiskizationsHelper
end

app/helpers/risks_helper.rb
module RisksHelper
end

app/helpers/user_steps_helper.rb
module UserStepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    
  </head>

  <body>

    <%= yield %>

    
    
  </body>
</html>

app/views/risks/index.html.erb
<h1>Реестр рисков</h1>

<%= link_to "Вввести новый фактор риска", new_risk_path %>

<br>
<table id="table1">
	<thead>
  <tr>
  	<th>№ </th>
    <th> Тип риска</th>
    <th> Наименование риска</th>
    <th> Последствия </th>   
  </tr>
 </thead>
 
 <tbody>
 <%i = 0%>
  <% @risk.each do |rc| %>
    <tr>
    	<%i = i + 1%>
      <td><%= i%></td>
      <td><%= rc.rtype %></td>	
      <td><%= rc.risk %></td>
      <td><%= rc.result %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/risks/new.html.erb
<h1>Добавить риск</h1>

<%= form_for @risk do |f| %>
  <% if @risk.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@risk.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @risk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Тип риска"%><br />
    <%= f.text_field :rtype %>
  </div>
  <div class="field">
    <%= f.label :"Наименование риска" %><br />
    <%= f.text_field :risk %>
  </div>
  <div class="field">
    <%= f.label :"Последствия" %><br />
    <%= f.text_area :result %>
  </div>

  <div class="actions">
    <%= f.submit "Сохранить" %>
  </div>
<% end %>

app/views/user_steps/_form.html.erb
<%= form_for @user, url: wizard_path do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= yield f %>
  
  <div class="actions">
    <%= f.submit "Continue" %>
    or <%= link_to "skip this step", next_wizard_path %>
  </div>
<% end %>

app/views/user_steps/personal.html.erb
<script>
	  
		$.ajax({
    success:function(){
        //your stuff
       $("#modelname").datepicker({ dateFormat: "dd.mm.yy" });
     }
 });
  
			
</script>

<div class="panel callout radius">
<h1>Введите свои личные данные.</h1>

<%= render layout: 'form' do |f| %>
  
    <%= f.label :"ФИО" %><br/>
    <%= f.text_field :name %>
  
    <%= f.label :"Дата рождения" %><br />
    
    <%= f.text_field :date_of_birth,:value => Time.now.strftime('%d.%m.%Y'),:id => "modelname" %>
    
    <%= f.label :"Электронная почта" %><br />
    <%= f.text_area :email, rows: 5 %>
  
<% end %>

</div>

app/views/user_steps/social.html.erb
<div class="panel callout radius">
<h1>I.Составление карточки профессиональных рисков</h1>

<%= render layout: 'form' do |f| %>
  <div class="field">
    <%= f.label :"Должность / профессия" %><br />
    <%= f.text_field :rabm %>
  </div>
  <div class="field">
    <%= f.label :" 1.Описание рабочих действий и зоны выполнения работ" %><br />
    <%= f.text_area :oprab %>
  </div>
  <div class="field">
    <%= f.label :" 2.Лица подверженные риску" %><br />
    <%= f.text_area :hlist %>
  </div>
<% end %>
</div>

app/views/user_steps/social1.html.erb
<div class="panel callout radius">

<%= render layout: 'form' do |f| %>
  <div class="field">
    <%= f.label :"Стандарты которые необходимо соблюдать" %><br />
    <%= f.text_area :lstand %>
  </div>
  <div class="field">
    <%= f.label :" Реальное состояние труда (выявленные нарушения требования стандартов)" %><br />
    <%= f.text_area :realst %>
  </div>
  
<% end %>

</div>

app/views/user_steps/social2.html.erb
<div class="panel callout radius">


<%= render layout: 'form' do |f| %>
  <h1>Реестр рисков</h1>



<br>
<table id="table1">
	<thead>
  <tr>
  	<th>№ </th>
    <th> Тип риска</th>
    <th> Наименование риска</th>
    <th> Последствия </th>
    <th>  </th>   
  </tr>
 </thead>
 
 <tbody>
 <%i = 0%>
 <%= hidden_field_tag "user[risk_ids][]", nil %>
  <% Risk.all.each do |risk| %>
    <tr>
    	<%i = i + 1%>
      <td><%= i%></td>
      <td><%= risk.rtype %></td>	
      <td><%= risk.risk %></td>
      <td><%= risk.result %></td>
      <td><%= check_box_tag "user[risk_ids][]", risk.id, @user.risk_ids.include?(risk.id), id: dom_id(risk) %> </td>
      <% label_tag dom_id(risk), risk.risk %>
    </tr>
  <% end %>
  </tbody>
</table>

  
<% end %>



</div>

app/views/user_steps/social3.html.erb
<div class="panel callout radius">

<h1>Оценка вероятности и последствий рисков</h1>
<%= form_for :riskizations, :url => {:action => 'update_rzs'} do %>
	<table>
		<tr>
		<th>№</th>
		<th>Наименование риска</th>
		<th>Вероятность</th>
		<th>Последствия</th>
		</tr>
		<% i=0%>
			<% @user.riskizations.each do |riskization| %>
			<%= fields_for "riskization[]", riskization do |riskization_fields| %>
			<tr>
				<% i=i+1%>
				<td><%= i %></td>

				<% @u = @user.risks.find(riskization.risk_id) %>
    			<td><%= @u.risk %></td>

				<td><%= riskization_fields.select(:rver,[["v",1],["b",2],["n",3],["m",4],["l",5]]) %></td>
				<td><%= riskization_fields.select(:rposl,[["v",1],["b",2],["n",3],["m",4],["l",5]]) %></td>
				<% session[:st] = 1 %> 
				
			</tr>
			<% end %>
			<% end %>
	</table>
	<%= submit_tag 'Continue' %>
	<%= link_to "skip this step", next_wizard_path %>
<% end %>

</div>

app/views/user_steps/social4.html.erb
<div class="panel callout radius">

<h1>Мероприятия по предотвращению рисков</h1>

<%= form_for :riskizations, :url => {:action => 'update_rzs'} do %>
	<table>
		<tr>
		<th>№</th>
		<th>Наименование риска</th>
		<th>Мероприятия по устранению</th>
		</tr>
		<% i=0%>
			<% @user.riskizations.each do |riskization| %>
			<%= fields_for "riskization[]", riskization do |riskization_fields| %>
			<tr>
				<% i=i+1%>
				<td><%= i %></td>

				<% @u = @user.risks.find(riskization.risk_id) %>
    			<td><%= @u.risk %></td>
				<td><%= riskization_fields.text_area :mpred %></td>
				<% session[:st] = 2 %>
			</tr>
			<% end %>
			<% end %>
	</table>
	<%= submit_tag 'Finish' %>
	
<% end %>

</div>

app/views/users/index.html.erb
<h1>Welcome</h1>

<% if current_user.nil? %>
  <p>Currently not signed in. <%= link_to "Sign Up", new_user_path %></p>
<% else %>
  <p>Currently signed in as:</p>
  <p><b>Email:</b> <%= current_user.email %></p>
  <p><b>Name:</b> <%= current_user.name %></p>
  <%= simple_format current_user.bio %>
  <p><%= link_to "Sign Up Again", new_user_path %></p>
<% end %>



<br>
<table id="table1">
	<thead>
  <tr>
  	<th>№ </th>
  	<th> Рабочее место / пост</th>
    <th> Name</th>
    <th> Date of birth</th>
    <th> E-mail</th>
    <th> Действия</th>
    <th> Действия</th>
    <th> Действияl</th>
    
    
  </tr>
 </thead>
 
 <tbody>
 <%i = 0%>
  <% @user.each do |fc| %>
    <tr>
    	<%i = i + 1%>
      <td><%= i%></td>
      <td><%= fc.rabm %></td>
      <td><%= fc.name %></td>	
      <td><%= fc.date_of_birth %></td>
      <td><%= fc.email %></td>
      <td><%= link_to "Показать", user_path(fc)%></td>
      <td><%= link_to "Изменить"%></td>
      <td><%= link_to "Удалить"%></td>
     
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="row">
 



<p>
  <strong>Дата : </strong>
  <%=  Date.today %>
</p>
 
	<center><h3>Карточка</h3></center>
	<center>
	 	по оценке профессиональных рисков
	</center>
	<center>
	 	(при проведении .............. работ)
	</center>
	<br><br>
	  <p>
        <strong>Описание рабочих действий и зоны выполнения работ:</strong><br>
        <%= @user.oprab %><br>
      </p> 
		<p><strong>Лица подвергающиеся риску:</strong><br>
				
         	<%= @user.hlist %><br>
         </p>				
  	<p>
  <strong>Список соблюдаемых стандартов</strong><br>
  <%= @user.lstand %>
	</p>
	<br>

 <p>
  <strong>Рабочее место:</strong>
  <%= @user.rabm%>
</p>

<p>
  <strong>Реальное состояние условий труда (выявленные нарушения требований стандартов)</strong><br>
  <%= @user.realst %>
</p>
 
<p>
  <strong>Список факторов риска:</strong>
  <p>
  	<table border="1">
		<tr>
		<th>Наименование риска</th>
		<th>Вероятность риска</th>
		<th>Последствия риска</th>
		<th>Уровень риска</th>
		<th>Меры предупреждения для уменьшения / устрашения выявленных рисков </th>
		</tr>
		<%s = ""%>
		<%s1 = ""%>
		<%s2 = ""%>
		<%s3 = ""%>
		
    <% for rc in @user.riskizations %>
    	<% @u = @user.risks.find(rc.risk_id) %>
    	<td><%= @u.risk %></td>
    	<% 
    	  ind = rc.rver.to_i + rc.rposl.to_i
    		    
    	    case ind
				when 1 .. 3
    				s =	"Незначительный риск"
				when 4 .. 5
    				s = "Приемлемый риск"
				when 6 .. 7
    				s = "Терпимый риск"
				when 8 .. 9
    				s = "Значительный риск"
				else
    				s = "Недопустимый риск"
			end	
    	 %>
    	 <% 
    	  ind1 = rc.rver.to_i 
    		    
    	    case ind1
				when 1
    				s1 = "Маловероятно"
				when 2
    				s1 = "Очень редко"
				when 3
    				s1 = "Редко"
				when 4
    				s1 = "Вероятно"
				else
    				s1 = "Очень вероятно"
			end	
    	 %>
    	 <% 
    	  ind2 = rc.rposl.to_i 
    		    
    	    case ind2
				when 1
    				s2 = "Легкие"
				when 2
    				s2 = "Умеренные"
				when 3
    				s2 = "Серьезные"
				when 4
    				s2 = "Очень серьезные"
				else
    				s2 = "Смертельно"
			end	
    	 %>
    	 <td><%= s1 %></td>
    	 <td><%= s2 %></td>
    	 <td><%= s %></td>
    	 <td><%= rc.mpred %></td>
    	</tr>
	  <% end %>
 	</table>
  </p>   
</p>




<p>
  
</p>

</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>